// Generated by CoffeeScript 2.5.1
var Config;

export default Config = {
  port: 9010,
  jwt: {
    keys: ['insecure secret'],
    algorithm: 'HS512'
  },
  tls: {
    certPath: 'C:\\Certbot\\live\\dev.ought.is\\fullchain.pem',
    keyPath: 'C:\\Certbot\\live\\dev.ought.is\\privkey.pem'
  }
};

export var loadConfig = async function(path) {
  var config, k, results, v;
  ({
    default: config
  } = (await import(path)));
  results = [];
  for (k in config) {
    v = config[k];
    results.push(Config[k] = v);
  }
  return results;
};
