// Generated by CoffeeScript 2.5.1
var Config;

export default Config = {};

export var loadConfig = async function(path) {
  var config, k, results, v;
  ({
    default: config
  } = (await import(path)));
  results = [];
  for (k in config) {
    v = config[k];
    results.push(Config[k] = v);
  }
  return results;
};
