// Generated by CoffeeScript 2.5.1
var Oak;

import {
  Application,
  Router,
  send
} from "https://deno.land/x/oak@v6.2.0/mod.ts";

Oak = {Application, Router, send};

import * as fs from "https://deno.land/std@0.69.0/fs/mod.ts";

export {
  Oak,
  fs
};
