// Generated by CoffeeScript 2.5.1
import {
  Api
} from '../node_modules/ur/deno/api.js';

Api.router.prefix('/api/v1');

Api.serveDataObject('global', './data/global');

Api.serveDataObject('themes', './data/themes');

Api.serveDataObject('cms', './data/cms');

Api.serveDataObject('pages', './data/pages');

Api.serve('./public');

(async function() {
  console.log('Listening on', 9010);
  return (await Api.host(9010));
})();
